### ISSUE TITLE
Request for PyPi release

### ISSUE THREAD

**Issue by shimwell** [Peque/sphinxcadquery#26]
Thanks for working through the updates for Sphinx v4.0.0, just wondering if there could be another PyPi release.

To pitch in and help I can offer a PR with a GitHub Action that would automate the package creation and uploading to PyPi

All the would be needed is a new GitHub Secret called ```PYPI_API_TOKEN``` and it can be automatically triggered on GitHub releases

```
# This yml file will trigger a Github Actions event that builds and upload the
# Python package to PiPy. This makes use of Twine and is triggered when a push
# to the master branch occures. For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
```

Let me know if you think this is worth a PR
